medical_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: meron
      port: 5432
      dbname: medical_db
      schema: public
      threads: 1
  target: dev