version: 2

models:
  - name: dim_channels
    description: "Dimension table containing metadata for each Telegram channel."
    columns:
      - name: channel_key
        description: "Primary key: md5 hash of the channel name."
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "The unique name of the Telegram channel."
      - name: channel_type
        description: "Category of the channel (Pharmaceutical, Cosmetics, Medical)."
      - name: first_post_date
        description: "The date of the earliest message collected from this channel."
      - name: last_post_date
        description: "The date of the most recent message collected from this channel."
      - name: total_posts
        description: "Total count of messages ingested from this channel."
      - name: avg_views
        description: "The average view count per post for this channel."

  - name: dim_dates
    description: "Date dimension for time-based analytical slicing."
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD format."
        tests:
          - unique
          - not_null
      - name: full_date
        description: "The actual date value."
      - name: is_weekend
        description: "Boolean flag indicating if the date falls on a Saturday or Sunday."

  - name: fct_messages
    description: "Fact table containing individual message metrics and links to dimensions."
    columns:
      - name: message_id
        description: "Unique identifier for each message."
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels."
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates."
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key